repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-merge-conflict
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.47.0
    hooks:
      - id: terraform_fmt
      # TODO: Uncomment line below in real repo
      #- id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint
      - id: checkov
  #- repo: git://github.com/dnephin/pre-commit-golang
    #rev: v0.3.5
    #hooks:
      #- id: go-fmt
      #- id: go-lint
